fix recommendation about orange line
pat-s/xaringan-metropolis pull request #7
Opened 2019-10-17 18:49 UTC by Enchufa2

The previous recommendation only worked well for 4:3 presentations. The new recommendation works well too for 16:9 (and virtually for any other ratio).

2019-10-17 19:10 UTC, Enchufa2 commented
We could even add the line to the CSS if you wish. I usually add the following in my presentations:

```css
hr {
  margin: 1em 15px 0 15px;
  border: none;
  background-color: #EB811B;
  color: #EB811B;
  height: 1px;
}
```

and then I only need:

```yaml
subtitle: "some subtitle <hr>
```

What do you think?

2019-10-19 12:55 UTC, pat-s commented
> We could even add the line to the CSS if you wish

This means adding it to the subtitle css class? Sure, go ahead 🚀. As said, this theme was nothing more than a dirty hack back then. Happy seeing it getting professionalized 👍

2019-10-19 20:39 UTC, Enchufa2 commented
There you go. Now, an orange line is automatically added under the subtitle in the title slide. To add an orange line in an `inverse` slide, just add the new `mline` class. Also, `<hr>` is available, with the same aesthetics, to be manually added wherever the user wants. I've updated the Rmd to reflect these changes. I haven't updated the images though.

2019-10-20 09:33 UTC, pat-s requested changes
Thanks! Looks good. Just a minor change and then we're good to go. 

Simplifies usage and makes it more flexible. Thanks!

2019-10-20 09:45 UTC, Enchufa2 commented
Sorry, I'm probably missing something, but what's the requested change? I don't see any comments in the "Files changed" tab.

2019-10-20 09:55 UTC, pat-s commented
Oh sorry, something got missing. Maybe I forgot to press enter.

I meant to use the following notation

```css
    css: 
      - default
      - mtheme.css
      - fonts_mtheme.css
```

for the CSS block. That's it. Sorry for the confusion.

2019-10-20 09:59 UTC, Enchufa2 commented
Done!

2019-10-21 13:43 UTC, pat-s approved these changes

2019-10-21 13:43 UTC, merged